Repository Pi-Squared-Network/pi2, pull requests merged in 2023-12, with the labels that each got.

#584 Add an `optimize` option flag and refactor for clarity
  Makefile
  generation/src/proof_generation/metamath/translate.py
  generation/src/proof_generation/proof.py
Labels: automerge

#534 Add the CSL examples in Cairo
  .gitignore
  cairo/csl-examples/bench.sh
  cairo/csl-examples/perceptron/Scarb.lock
  cairo/csl-examples/perceptron/Scarb.toml
  cairo/csl-examples/perceptron/src/lib.cairo
  cairo/csl-examples/perceptron/src/perceptron.cairo
  cairo/csl-examples/svm5/Scarb.lock
  cairo/csl-examples/svm5/Scarb.toml
  cairo/csl-examples/svm5/src/lib.cairo
  cairo/csl-examples/svm5/src/svm5.cairo
  cairo/csl-examples/transfer/Scarb.lock
  cairo/csl-examples/transfer/Scarb.toml
  cairo/csl-examples/transfer/src/lib.cairo
  cairo/csl-examples/transfer/src/transfer.cairo
  cairo/csl-examples/transfer5000/Scarb.lock
  cairo/csl-examples/transfer5000/Scarb.toml
  cairo/csl-examples/transfer5000/src/lib.cairo
  cairo/csl-examples/transfer5000/src/transfer5000.cairo
Labels: automerge, experiment

#591 Split Performance Numbers for Lurk
  Performance.md
  lurk/bench.sh
  lurk/bench_csl.sh
  lurk/bench_pi2.sh
  lurk/csl-examples/perceptron.lurk
  lurk/csl-examples/svm5.lurk
  lurk/csl-examples/transfer.lurk
  lurk/csl-examples/transfer5000.lurk
Labels: automerge, lurk-checker

#597 Fixing typo on `perceptron.cairo`
  cairo/csl-examples/perceptron/src/perceptron.cairo
Labels: automerge

#551 Implement processing simplification batches but without proving
  generation/src/proof_generation/k/execution_proof_generation.py
  generation/src/proof_generation/k/kore_convertion/language_semantics.py
  generation/src/proof_generation/pattern.py
  generation/src/proof_generation/proofs/kore.py
  generation/src/tests/unit/test_execution_proof_generation.py
  generation/src/tests/unit/test_kore_language_semantics.py
  generation/src/tests/unit/test_pattern.py
Labels: automerge, generation

#585 Compose instantiation optimizer with memoization when optimizing proofs
  Makefile
  generation/src/proof_generation/interpreter_transformer.py
  generation/src/proof_generation/metamath/translate.py
  generation/src/proof_generation/optimizing_interpreters.py
  generation/src/proof_generation/proof.py
  proofs/propositional.ml-claim
  proofs/propositional.pretty-claim
  proofs/propositional.pretty-proof
  proofs/small_theory.pretty-gamma
  proofs/small_theory.pretty-proof
  proofs/substitution.ml-claim
  proofs/substitution.ml-gamma
  proofs/substitution.pretty-claim
  proofs/substitution.pretty-gamma
  proofs/substitution.pretty-proof
Labels: automerge

#590 Update dependency: deps/pyk_release
  deps/k_release
  deps/pyk_release
  generation/poetry.lock
  generation/pyproject.toml
Labels: automerge

#599 Memoizer: Remove unneeded logic for handling `None`
  generation/src/proof_generation/optimizing_interpreters.py
Labels: automerge

#582 Adding `Lurk Tests` Job in Check.yml
  .github/workflows/daily-check.yml
Labels: automerge, blocked, debt

#606 Rename evar_is_free to evar_is_fresh
  generation/src/proof_generation/basic_interpreter.py
  generation/src/proof_generation/pattern.py
Labels: automerge

#605 The implementation of 2/3 subtasks from #473 (prove_simplification)
  generation/src/proof_generation/k/execution_proof_generation.py
  generation/src/proof_generation/proofs/kore.py
  generation/src/tests/unit/test_kore_lemmas.py
  proofs/generated-from-k/double-rewrite/foo-a.double-rewrite.ml-claim
  proofs/generated-from-k/double-rewrite/foo-a.double-rewrite.ml-gamma
  proofs/generated-from-k/double-rewrite/foo-a.double-rewrite.ml-proof
  proofs/generated-from-k/double-rewrite/foo-a.double-rewrite.pretty-gamma
  proofs/generated-from-k/double-rewrite/foo-a.double-rewrite.pretty-proof
  proofs/generated-from-k/empty.imp5.ml-claim
  proofs/generated-from-k/empty.imp5.ml-gamma
  proofs/generated-from-k/empty.imp5.ml-proof
  proofs/generated-from-k/empty.imp5.pretty-gamma
  proofs/generated-from-k/empty.imp5.pretty-proof
  proofs/generated-from-k/foo-a.double-rewrite.ml-claim
  proofs/generated-from-k/foo-a.double-rewrite.ml-gamma
  proofs/generated-from-k/foo-a.double-rewrite.ml-proof
  proofs/generated-from-k/foo-a.double-rewrite.pretty-gamma
  proofs/generated-from-k/foo-a.double-rewrite.pretty-proof
  proofs/generated-from-k/foo-a.single-rewrite.ml-claim
  proofs/generated-from-k/foo-a.single-rewrite.ml-gamma
  proofs/generated-from-k/foo-a.single-rewrite.ml-proof
  proofs/generated-from-k/foo-a.single-rewrite.pretty-gamma
  proofs/generated-from-k/foo-a.single-rewrite.pretty-proof
  proofs/generated-from-k/imp5/empty.imp5.ml-claim
  proofs/generated-from-k/imp5/empty.imp5.ml-gamma
  proofs/generated-from-k/imp5/empty.imp5.ml-proof
  proofs/generated-from-k/imp5/empty.imp5.pretty-gamma
  proofs/generated-from-k/imp5/empty.imp5.pretty-proof
  proofs/generated-from-k/single-rewrite/foo-a.single-rewrite.ml-claim
  proofs/generated-from-k/single-rewrite/foo-a.single-rewrite.ml-gamma
  proofs/generated-from-k/single-rewrite/foo-a.single-rewrite.ml-proof
  proofs/generated-from-k/single-rewrite/foo-a.single-rewrite.pretty-gamma
  proofs/generated-from-k/single-rewrite/foo-a.single-rewrite.pretty-proof
Labels: automerge

#603 Fix lurk table
  Performance.md
Labels: automerge

#613 Implement Cairo0 CSL examples
  Performance.md
  cairo/csl-examples/cairo0/bench.sh
  cairo/csl-examples/cairo0/perceptron.cairo
  cairo/csl-examples/cairo0/svm5.cairo
  cairo/csl-examples/cairo0/transfer.cairo
  cairo/csl-examples/cairo0/transfer5000.cairo
  cairo/csl-examples/cairo2/bench.sh
  cairo/csl-examples/cairo2/perceptron/Scarb.lock
  cairo/csl-examples/cairo2/perceptron/Scarb.toml
  cairo/csl-examples/cairo2/perceptron/src/lib.cairo
  cairo/csl-examples/cairo2/perceptron/src/perceptron.cairo
  cairo/csl-examples/cairo2/svm5/Scarb.lock
  cairo/csl-examples/cairo2/svm5/Scarb.toml
  cairo/csl-examples/cairo2/svm5/src/lib.cairo
  cairo/csl-examples/cairo2/svm5/src/svm5.cairo
  cairo/csl-examples/cairo2/transfer/Scarb.lock
  cairo/csl-examples/cairo2/transfer/Scarb.toml
  cairo/csl-examples/cairo2/transfer/src/lib.cairo
  cairo/csl-examples/cairo2/transfer/src/transfer.cairo
  cairo/csl-examples/cairo2/transfer5000/Scarb.lock
  cairo/csl-examples/cairo2/transfer5000/Scarb.toml
  cairo/csl-examples/cairo2/transfer5000/src/lib.cairo
  cairo/csl-examples/cairo2/transfer5000/src/transfer5000.cairo
Labels: automerge, experiment

#611 Update dependency: deps/pyk_release
  deps/pyk_release
  generation/poetry.lock
  generation/pyproject.toml
Labels: automerge

#616 Remove sorts from kore-and and kore-or
  generation/src/proof_generation/k/kore_convertion/language_semantics.py
  generation/src/proof_generation/proofs/kore.py
  generation/src/tests/unit/test_execution_proof_generation.py
  generation/src/tests/unit/test_kore_language_semantics.py
  proofs/generated-from-k/double-rewrite/foo-a.double-rewrite.ml-claim
  proofs/generated-from-k/double-rewrite/foo-a.double-rewrite.ml-gamma
  proofs/generated-from-k/double-rewrite/foo-a.double-rewrite.pretty-claim
  proofs/generated-from-k/double-rewrite/foo-a.double-rewrite.pretty-gamma
  proofs/generated-from-k/double-rewrite/foo-a.double-rewrite.pretty-proof
  proofs/generated-from-k/foo-a.double-rewrite.ml-claim
  proofs/generated-from-k/foo-a.double-rewrite.ml-gamma
  proofs/generated-from-k/foo-a.double-rewrite.pretty-claim
  proofs/generated-from-k/foo-a.double-rewrite.pretty-gamma
  proofs/generated-from-k/foo-a.double-rewrite.pretty-proof
  proofs/generated-from-k/imp5/empty.imp5.ml-claim
  proofs/generated-from-k/imp5/empty.imp5.ml-gamma
  proofs/generated-from-k/imp5/empty.imp5.pretty-claim
  proofs/generated-from-k/imp5/empty.imp5.pretty-gamma
  proofs/generated-from-k/imp5/empty.imp5.pretty-proof
  proofs/generated-from-k/single-rewrite/foo-a.single-rewrite.ml-claim
  proofs/generated-from-k/single-rewrite/foo-a.single-rewrite.ml-gamma
  proofs/generated-from-k/single-rewrite/foo-a.single-rewrite.pretty-claim
  proofs/generated-from-k/single-rewrite/foo-a.single-rewrite.pretty-gamma
  proofs/generated-from-k/single-rewrite/foo-a.single-rewrite.pretty-proof
Labels: automerge, enhancement

#615 Update risc0 transfer5000 direct implementation and update performance numbers
  Performance.md
  risc0/bench.sh
  risc0/csl-examples/guest/src/transfer.rs
  risc0/csl-examples/guest/src/transfer5000.rs
  risc0/csl-examples/src/main.rs
  risc0/pi2/src/main.rs
Labels: automerge, experiment

#619 Fix ZKLLVM and Lurk examples
  Performance.md
  lurk/csl-examples/transfer.lurk
  lurk/csl-examples/transfer5000.lurk
  zkllvm/csl-zkllvm/build.sh
  zkllvm/csl-zkllvm/transfer/transfer_input.json
  zkllvm/csl-zkllvm/transfer/transfer_test.cpp
  zkllvm/csl-zkllvm/transfer5000/transfer5000_input.json
  zkllvm/csl-zkllvm/transfer5000/transfer5000_test.cpp
Labels: automerge, experiment

#623 Fix dict order relevance bug
  generation/src/proof_generation/pattern.py
Labels: automerge

#620 Implement function for proving the equation of of a given equality rule
  generation/src/proof_generation/k/execution_proof_generation.py
  generation/src/proof_generation/proofs/kore.py
  generation/src/tests/unit/test_execution_proof_generation.py
  generation/src/tests/unit/test_kore_lemmas.py
  proofs/generated-from-k/double-rewrite/foo-a.double-rewrite.ml-gamma
  proofs/generated-from-k/double-rewrite/foo-a.double-rewrite.ml-proof
  proofs/generated-from-k/double-rewrite/foo-a.double-rewrite.pretty-gamma
  proofs/generated-from-k/double-rewrite/foo-a.double-rewrite.pretty-proof
  proofs/generated-from-k/imp5/empty.imp5.ml-gamma
  proofs/generated-from-k/imp5/empty.imp5.ml-proof
  proofs/generated-from-k/imp5/empty.imp5.pretty-gamma
  proofs/generated-from-k/imp5/empty.imp5.pretty-proof
  proofs/generated-from-k/single-rewrite/foo-a.single-rewrite.ml-gamma
  proofs/generated-from-k/single-rewrite/foo-a.single-rewrite.ml-proof
  proofs/generated-from-k/single-rewrite/foo-a.single-rewrite.pretty-gamma
  proofs/generated-from-k/single-rewrite/foo-a.single-rewrite.pretty-proof
Labels: automerge, generation

#609 Implemementing the skeleton version of Cairo Checker
  cairo/Scarb.toml
  cairo/cairo_project.toml
  cairo/src/lib.cairo
  cairo/src/pattern.cairo
  cairo/src/stack.cairo
  cairo/src/term.cairo
  cairo/src/verifier.cairo
Labels: automerge, cairo-checker

#622 Update dependency: deps/pyk_release
  deps/k_release
  deps/pyk_release
  generation/poetry.lock
  generation/pyproject.toml
Labels: automerge

#630 Drop unused sorts from `kore_next` and `kore_bottom` notations
  generation/src/proof_generation/k/kore_convertion/language_semantics.py
  generation/src/proof_generation/llvm_proof_hint_printer.py
  generation/src/proof_generation/proofs/kore.py
  proofs/generated-from-k/double-rewrite/foo-a.double-rewrite.ml-claim
  proofs/generated-from-k/double-rewrite/foo-a.double-rewrite.ml-gamma
  proofs/generated-from-k/double-rewrite/foo-a.double-rewrite.pretty-claim
  proofs/generated-from-k/double-rewrite/foo-a.double-rewrite.pretty-gamma
  proofs/generated-from-k/double-rewrite/foo-a.double-rewrite.pretty-proof
  proofs/generated-from-k/foo-a.double-rewrite.ml-claim
  proofs/generated-from-k/foo-a.double-rewrite.ml-gamma
  proofs/generated-from-k/foo-a.double-rewrite.ml-proof
  proofs/generated-from-k/foo-a.double-rewrite.pretty-claim
  proofs/generated-from-k/foo-a.double-rewrite.pretty-gamma
  proofs/generated-from-k/foo-a.double-rewrite.pretty-proof
  proofs/generated-from-k/imp5/empty.imp5.ml-claim
  proofs/generated-from-k/imp5/empty.imp5.ml-gamma
  proofs/generated-from-k/imp5/empty.imp5.pretty-claim
  proofs/generated-from-k/imp5/empty.imp5.pretty-gamma
  proofs/generated-from-k/imp5/empty.imp5.pretty-proof
  proofs/generated-from-k/single-rewrite/foo-a.single-rewrite.ml-claim
  proofs/generated-from-k/single-rewrite/foo-a.single-rewrite.ml-gamma
  proofs/generated-from-k/single-rewrite/foo-a.single-rewrite.pretty-claim
  proofs/generated-from-k/single-rewrite/foo-a.single-rewrite.pretty-gamma
  proofs/generated-from-k/single-rewrite/foo-a.single-rewrite.pretty-proof
Labels: automerge

#631 Preparing Cairo Checker to implement `execute_instructions`
  cairo/.cairofmtignore
  cairo/README.md
  cairo/Scarb.toml
  cairo/cairo_project.toml
  cairo/src/lib.cairo
  cairo/src/pattern.cairo
  cairo/src/stack.cairo
  cairo/src/term.cairo
  cairo/src/verifier.cairo
Labels: automerge, cairo-checker

#635 Update dependency: deps/pyk_release
  deps/k_release
  deps/pyk_release
  generation/poetry.lock
  generation/pyproject.toml
Labels: automerge

#632 Cairo checker execute instructions 2
  cairo/src/pattern.cairo
  cairo/src/term.cairo
  cairo/src/verifier.cairo
Labels: automerge, cairo-checker

#638 Sync wellformedness checking with R0 implementation and add wellformedness checking for Notation
  generation/src/proof_generation/pattern.py
  generation/src/tests/unit/test_pattern.py
Labels: automerge

#625 Update scripts to build with zkLLVM
  zkllvm/build.sh
  zkllvm/csl-zkllvm/build.sh
Labels: automerge, debt

#640 Implement Pattern Utility Functions
  cairo/src/pattern.cairo
  cairo/src/verifier.cairo
Labels: automerge, cairo-checker

#607 Fix xsubst functions for Instantiate in order to preserve notations
  generation/src/proof_generation/aml/notation.py
  generation/src/proof_generation/aml/syntax.py
  generation/src/tests/unit/test_pattern.py
Labels: automerge

#639 Update dependency: deps/pyk_release
  deps/k_release
  deps/pyk_release
  generation/poetry.lock
  generation/pyproject.toml
Labels: automerge

#649 Update dependency: deps/pyk_release
  deps/k_release
  deps/pyk_release
  generation/poetry.lock
  generation/pyproject.toml
Labels: automerge

#654 Implement apply_esubst and apply_ssubst
  cairo/src/verifier.cairo
Labels: automerge

#657 Complete the `instantiate_internal` function
  cairo/src/verifier.cairo
Labels: automerge, cairo-checker

#660 Using `std::memset` instead of our own `memset_` implementation.
  cpp/include/data_structures.hpp
  cpp/src/lib.hpp
Labels: automerge, checker

#662 Implement execute_inst::Symbol and execute_inst::App
  cairo/src/pattern.cairo
  cairo/src/verifier.cairo
Labels: automerge, cairo-checker

#652 Update dependency: deps/pyk_release
  deps/k_release
  deps/pyk_release
  generation/poetry.lock
  generation/pyproject.toml
Labels: automerge

#658 Add support for lifting simplification proofs to rewrites
  generation/src/proof_generation/k/execution_proof_generation.py
  generation/src/proof_generation/k/kore_convertion/language_semantics.py
  generation/src/proof_generation/proof.py
  generation/src/proof_generation/proofs/kore.py
  generation/src/proof_generation/proofs/substitution.py
  generation/src/tests/unit/test_execution_proof_generation.py
  generation/src/tests/unit/test_kore_language_semantics.py
  generation/src/tests/unit/test_kore_lemmas.py
Labels: automerge

#665 Introducing Cairo Pi2 Implementation Inputs
  cairo/src/lib.cairo
  cairo/src/test_batch_transfer_goal.cairo
  cairo/src/test_impreflex.cairo
  cairo/src/test_perceptron_goal.cairo
  cairo/src/test_svm_goal.cairo
  cairo/src/test_transfer_goal.cairo
  cairo/src/verifier.cairo
Labels: automerge, cairo-checker

#664 Add code for processing functional events and tests for traces with them
  generation/k-benchmarks/tree-reverse-without-integers/simplify.tree-reverse-without-integers
  generation/src/proof_generation/k/execution_proof_generation.py
  generation/src/proof_generation/k/kore_convertion/rewrite_steps.py
  generation/src/tests/integration/rewrite/test_llvm_proof_generator.py
  generation/src/tests/integration/rewrite/test_llvm_proof_hint.py
  generation/src/tests/unit/test_execution_proof_generation.py
  proofs/proof-hints/tree-reverse-without-integers/simplify.tree-reverse-without-integers.hints.pretty
Labels: automerge

#669 Move claims to `BasicInterpreter`; misc refactorings
  generation/src/proof_generation/aml/syntax.py
  generation/src/proof_generation/aml/utils.py
  generation/src/proof_generation/interpreter/basic_interpreter.py
  generation/src/proof_generation/interpreter/stateful_interpreter.py
  generation/src/tests/unit/test_pattern.py
Labels: automerge

#667 Update dependency: deps/pyk_release
  deps/k_release
  deps/pyk_release
  generation/poetry.lock
  generation/pyproject.toml
Labels: automerge

#671 Update dependency: deps/pyk_release
  deps/k_release
  deps/pyk_release
  generation/poetry.lock
  generation/pyproject.toml
Labels: automerge

#672 Update dependency: deps/pyk_release
  deps/k_release
  deps/pyk_release
  generation/poetry.lock
  generation/pyproject.toml
Labels: automerge
